### ISSUE TITLE
turn into library-only

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-status#231]
this project is a library (deployed to npm) and also a deployed action.
as action, it currently doesn't do much, but to check that it works. however, as library, it is embedded in almost every other action in helix, so it is implicitly monitored there.

### why now?
with the move to github actions for npm deployment (https://github.com/adobe/helix-home/issues/166) having a dual project is a bit tricky. so it would be easier to get rid of the action deployment

### alternative
split into lib and action and create 2 projects.

**Comment by rofe** [comment]
Just as an FYI: we currently use the action for [reporting](https://github.com/adobe/helix-status/blob/main/.circleci/config.yml#L74) I/O Runtime status on https://status.project-helix.io/#. Precisely because it's generic and doesn't do anything on its own (other than being invoked). If we remove it as an action, we'll have to find another way to monitor I/O Runtime and track historical uptime.

**Comment by tripodsan** [comment]
ok, then I guess it's best to create a own repository, eg. `helix-runtime-status`

**Comment by trieloff** [comment]
Why can't we deploy and release separately from the same repository?

**Comment by tripodsan** [comment]
> Why can't we deploy and release separately from the same repository?

because:
- i don't want to add the wsk creds to github
- have a separation from action to library is anyways a good thing. otherwise each update to the action triggers a myriad of dependency updates

we could:
- configure the circleci to ract on the release commit message from github and then deploy the action.....
- or create a multi-package project in this repository, one for the lib and one for the action

**Comment by tripodsan** [comment]
I looked into creating a setup for multi-package project, but it's a bit too complicated.
see https://medium.com/labs42/monorepo-with-circleci-conditional-workflows-69e65d3f1bd0

maybe the best approach is to deploy via github action....

**Comment by tripodsan** [comment]
won't fix.
