### ISSUE TITLE
How to specify runtime-specific test URLs?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-status#285]
Related to #284: in order to test all services, we need to specify runtime-specific URLs so that OW is testing OW services and AWS is testing AWS services. Not yet sure how to do this.

**Comment by tripodsan** [comment]
isn't it possible to add functions to the check entries that can change the request before sending it?
maybe we can alter the URL to use the env internal endpoints, like in:

https://github.com/adobe/helix-deploy/blob/main/src/template/resolver.js

i.e. the url to check would be an action name, and it uses the `resolver` to construct the endpoint

**Comment by tripodsan** [comment]
closing as won't fix.
