### ISSUE TITLE
Add `/pingdom_custom.xml` that always returns 200.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-status#30]
**Is your feature request related to a problem? Please describe.**
in #21, we reverted to behaviour respond with an error status code, which makes the pingdom custom checks fail (see #12). In order to re-enable the custom checks, we should change the behavior for a specific url. suggest:

`/_status_check/pingdom_custom.xml`

**Comment by stefan-guggisberg** [comment]
Why would we want to support the Pingdom Custom checks? They don't work for our use case (monitoring and troubleshooting/RCA), as explained in detail in #21.

**Comment by trieloff** [comment]
Not needed anymore.
