### ISSUE TITLE
Helix Status fails to create new relic monitor due to deprecated monitor location

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-status#50]
```bash
$ node ./node_modules/.bin/synthetics-check update https://adobeioruntime.net/api/v1/web/helix/helix-services/`node -e "console.log(require('./package.json').name.replace('@adobe/helix-', ''))"`@v`node -e "console.log(require('./package.json').version.match(/^[0-9]+.[0-9]+/)[0])"`/_status_check/healthcheck.json
Creating a new monitor @adobe/helix-service
Monitor creation failed 400 - {"errors":[{"error":"The 'LINODE_US_WEST_1' location is deprecated and can no longer be added."},{"error":"The 'LINODE_US_CENTRAL_1' location is deprecated and can no longer be added."},{"error":"The 'LINODE_US_EAST_1' location is deprecated and can no longer be added."}],"count":3}
Exited with code 1
```

https://circleci.com/gh/adobe/helix-run-query/5

**Comment by trieloff** [comment]
@rofe I think this is just a matter of getting the new list of valid locations and hard-coding it. A possible improvement would be to query for valid locations first.

**Comment by rofe** [comment]
@trieloff correct. New Relic recently deprecated a number of locations. We need to slightly dial back on number of locations anyway, see [here](https://github.com/adobe/helix-status/blob/f12496d54fba0891fcee305000e2cdad83cd0b01/src/newrelic/synthetics.js#L20) for my current proposal (I'm refactoring the automation in this [PR](https://github.com/adobe/helix-status/pull/47), feedback welcome of course :)

In the meantime, I'll look into it.
