### ISSUE TITLE
Extract and store Activation Metadata

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-status#75]
The first request we are making provides us with the `x-activation-id` header, which we could use to get additional metadata from the action, similar to `wsk activation get <id>`. We'd have to make the underlying HTTP request ourselves, but it should be relatively easy to find out the correct URL.

**Comment by trieloff** [comment]
@rofe 

I found some more interesting annotations:

```json
"annotations": [
        {
            "key": "waitTime",
            "value": 87
        },
        {
            "key": "initTime",
            "value": 203
}}
```

**Comment by rofe** [comment]
> I found some more ...

Interesting, where? I haven't seen those yet... Either way, please review #77
