### ISSUE TITLE
move monitoring scripts to own repository

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-status#97]
**Is your feature request related to a problem? Please describe.**
this project mixes the runtime action code and the tooling scripts to manage the monitoring scripts in new relic and statuspage. IMO, those should not be mixed as their lifecycle is different.

**Describe the solution you'd like**
Ensure that this repository only produces 1 artifact which is the runtime action.
Move the `newrelic.js` and `statuspage.js` to their own repository (`helix-monitoring`) (maybe together with the orb).

/cc @rofe, @trieloff

**Comment by rofe** [comment]
- [ ] copy scripts to new repo
- [ ] publish new module to npm
- [ ] add new module as dependency
- [ ] remove scripts from this repo
